spring.application.name=consumer

logging.level.TransactionsService=info
logging.level.TaskExecutor=info

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:transactions}
spring.datasource.username=${DB_DEV_USERNAME:dev_user}
spring.datasource.password=${DB_DEV_PASSWORD:dev_password}
spring.datasource.hikari.schema=${DB_SCHEMA:transactions}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.format_sql=false
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.data.redis.host=${DB_REDIS_HOST:localhost}
spring.data.redis.port=${DB_REDIS_PORT:6379}