spring.application.name=producer

logging.level.Controller=info
logging.level.Service=info
logging.level.TransactionDAO=info

spring.data.redis.host=${DB_REDIS_HOST:localhost}
spring.data.redis.port=${DB_REDIS_PORT:6379}